FROM python:3.9-slim

# Устанавливаем mysql-client
RUN apt-get update && apt-get install -y default-mysql-client && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["./wait-for-mysql.sh", "db", "python", "main.py"]